### PR TITLE
Add crossplane dependencies to local testing

### PR DESCRIPTION
**Pull request by ccremer**
## Summary

* Adds Crossplane dependencies for testing locally in kind (Preparation for #17 )
* Adds integration test boilerplate (Preparation for #17 )

## Checklist

- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [x] Update tests.
- [x] Link this PR to related issues.

### CODE REVIEW

**Comment by Kidswiss** [comment]
Only tested the make targets so far and no code. Here are my findings so far:

`make build` creates a borked image, if run with macos. Didn't we fix that already somewhere? The image with `make local-install` seems fine though. So probably not that much of a deal.

The chart seems to have a problem when running `make local-install`:
```
helm upgrade --install provider-postgresql chart \
        --create-namespace --namespace postgresql-system \
        --set "operator.args[0]=--log-level=2" \
        --set "operator.args[1]=operator" \
        --set podAnnotations.date="Mon  9 May 2022 13:07:04 CEST" \
        --values /Users/simonbeck/repos/appcat/appcat-service-postgresql/.kind/webhook-values.yaml \
        --wait
Release "provider-postgresql" does not exist. Installing it now.
Error: clusterroles.rbac.authorization.k8s.io "provider-postgresql" already exists
gmake: *** [test/local.mk:27: local-install] Error 1
```
A subsequent `make local-install` fixes the problem though.

**Comment by Kidswiss** [comment]
> If you make cleaned the repo, then the binary built should be for macos (since it takes over GOOS and GOARCH). The base image (alpine:1.15) should be as well for darwin when you pull. 

Yeah that's the problem. Docker on MacOs is always in a linux VM, so the locally built bin won't work. `local-install` seems to override things to `linux` and `amd64` so then it works.

> Did you delete the kind cluster before as well to have a clear plate? I changed the way how clusterrole(binding) is applied.

Yes my start was a clean cluster, basically `make clean && make local-install`.

> Are you sure that's not a sentinel file skipping the targets?

First run:
```
helm upgrade --install provider-postgresql chart \
        --create-namespace --namespace postgresql-system \
        --set "operator.args[0]=--log-level=2" \
        --set "operator.args[1]=operator" \
        --set podAnnotations.date="Mon  9 May 2022 15:30:51 CEST" \
        --values /Users/simonbeck/repos/appcat/appcat-service-postgresql/.kind/webhook-values.yaml \
        --wait
Release "provider-postgresql" does not exist. Installing it now.
Error: clusterroles.rbac.authorization.k8s.io "provider-postgresql" already exists
gmake: *** [test/local.mk:27: local-install] Error 1
```

Second run:
```
helm upgrade --install provider-postgresql chart \
        --create-namespace --namespace postgresql-system \
        --set "operator.args[0]=--log-level=2" \
        --set "operator.args[1]=operator" \
        --set podAnnotations.date="Mon  9 May 2022 15:31:37 CEST" \
        --values /Users/simonbeck/repos/appcat/appcat-service-postgresql/.kind/webhook-values.yaml \
        --wait
Release "provider-postgresql" has been upgraded. Happy Helming!
```

The helm install seems to be running on every `make local-install`.

**Comment by ccremer** [comment]
@Kidswiss I've fixed the sed command as we've figured out in the call. Please try again.

**Comment by Kidswiss** [comment]
@ccremer seems to be working now.

**Comment by Kidswiss** [comment]
Would it make sense to integrate https://github.com/vshn/kindev here?

**Comment by ccremer** [comment]
> Would it make sense to integrate https://github.com/vshn/kindev here?

Not now. PR #27 depends on this and I don't want to rebase 20+ commits based on a completely new structure. Maybe after that.

**Comment by Kidswiss** [comment]
> Not now. PR https://github.com/vshn/appcat-service-postgresql/pull/27 depends on this and I don't want to rebase 20+ commits based on a completely new structure. Maybe after that.

Fine by me, we can do it later.

**Review by Kidswiss — APPROVED** [review]
Haven't had a look at the code in detail, but the most important make calls are working for MacOS.

**Pull request merged**
