### PR TITLE
Add K8up permissions to clusterrole

### PR DESCRIPTION
**Pull request by ccremer**
## Summary

* Updates the ClusterRole template after introduction of the new feature in #69 

### For Helm Chart changes

- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [x] PR contains the label `area:chart`
- [x] PR contains the chart label, e.g. `chart:provider-postgresql`
- [x] Variables are documented in the values.yaml using the format required by [Helm-Docs](https://github.com/norwoodj/helm-docs#valuesyaml-metadata).
- [x] Chart Version bumped if immediate release after merging is planned
- [x] I have run `make chart-docs`
- [x] Link this PR to related code release or other issues.

### CODE REVIEW

**Comment by ZuGao** [comment]
Can you also add pods and PVCs in this PR? Same permissions as Schedules

**Comment by ccremer** [comment]
> Can you also add pods and PVCs in this PR? Same permissions as Schedules

That requires the generator to be updated as well, which would be a code change that can't go into this PR.
If you create a PR that adds those permissions, I'm happy to rebase this PR on your PR.
See https://github.com/vshn/appcat-service-postgresql/blob/d3404861b869c27f4970913f6ee4e8720117e78f/operator/standalone/controller.go#L28-L39

**Review by ZuGao — APPROVED** [review]
LGTM

**Comment by ZuGao** [comment]
Let's not get confusing with this, lets merge it

**Pull request merged**
